version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: daniel
      MONGO_INITDB_ROOT_PASSWORD: daniel

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: daniel
      ME_CONFIG_MONGODB_ADMINPASSWORD: daniel
      ME_CONFIG_MONGODB_URL: mongodb://daniel:daniel@mongo:27017/